### ISSUE TITLE
get npm publish rights

### ISSUE THREAD

**Issue by cdaringe** [node-swig/swig#7]

**Comment by cdaringe** [comment]
@paularmstrong, would you be willing to add additional collaborators to swig on npm for publish right?

**Comment by walfly** [comment]
@cdaringe have you considered just publishing it as a separate package?

**Comment by cdaringe** [comment]
yes, but I would strongly prefer to keep it the same.  I've tried reaching out to @paularmstrong a couple of times without response.  we may consider following the npm package name resolution process

**Comment by paularmstrong** [comment]
Hey all, I'd rather keep things separate for now. Please use a different package name if possible.

**Comment by chielkunkels** [comment]
Have we picked up a new name yet for swig? I'd like to continue using it if at all possible. I know I can install a version off of github so that'll do for now, but I guess we can choose a new name and be done with it?

**Comment by walfly** [comment]
How about node-swig?

**Comment by Noiwex** [comment]
call it swig2, guys

**Comment by cdaringe** [comment]
@paulcpederson @Lochlan, thoughts?

**Comment by paulcpederson** [comment]
@cdaringe personally, I think node-swig is fine. But here is a random list of other names:

swig2, swiggy, swigg, swigs, swigly, 2wig, swiig, swg, sw1g

**Comment by paulcpederson** [comment]
5wig

**Comment by Lochlan** [comment]
I'm fine with whatever, although I don't necessarily think it's very relevant right now since I don't think there's been a reason to cut a release?

To bikeshed: I think "node-swig" is redundant, and although I'm fine with it as the org name for this fork I don't think it is a great npm package name.  If I could just pick I would probably go with the cheeky "swig-maintained," since that seems to be the purpose of this fork.  Or maybe "swig2" if we want to go there.  I think right now we're just trying to be "swig, but not dead," so I would favor naming that signifies that.

Ultimately I think that it's early days, and if we continue with the efforts begun here (and do indeed have a reason to cut a release) we can probably convince @paularmstrong to pass the mantle of the "swig" name.  But if we can't, that's fine with me too, forking is what open source is all about! :)  Actually, it might be interesting to consider something radically different if we can determine what our specific goals are for this fork.

**Comment by webxl** [comment]
Why not swig-templates?

**Comment by paularmstrong** [comment]
Just my 2¢, I wouldn't choose [swig](https://en.wikipedia.org/wiki/SWIG) if I were still doing this. People get really confused.

**Comment by webxl** [comment]
Why was swig picked in the first place @paularmstrong? 

I wasn't confused, but I had no experience with the other SWIG either. So I guess how it's we're introduced to the project. For me, it was the metalsmith project. If we go to a new name, then it might just take some announcements to projects like metalsmith that there's a maintained replacement.

If it stays swig, I like appending "-templates" because in a long list of imports, a 4 letter verb easily gets lost.

**Comment by paularmstrong** [comment]
[Twig](http://twig.sensiolabs.org) -> I was drunk and wanted to "take a swig"

**Comment by paulcpederson** [comment]
swig-templates actually solves both problems as it indicates that it isn't traditional SWIG and distinguishes it from the current package. @cdaringe I think that would work well. 

Added bonus if people search "swig" on npm it will be there, and if people search "templates" it will also be there

**Comment by cdaringe** [comment]
@paulcpederson, ya.

There's no right or wrong answers here.  swig-templates it is
